### PR TITLE
Add in-code version tagging; reorganize into a package with setup.py

### PR DESCRIPTION
**Pull request by davidlmobley**
This PR attempts to:

- Reorganize the package into a modular structure with `solvationtoolkit` as the package name and `solvated_mixtures` the main module
- Add a `setup.py` for installation
- Add a version tag in `setup.py` - currently set to 0.2.0; would be updated to a development version after this is merged

Additionally, there are some updates to documentation.

@nividic - this is my first time creating a `setup.py` and reorganizing accordingly. Can you check for me? (I adapted one of yours). 

Also, we'll see if this passes tests on Travis. It does on my computer.

### CODE REVIEW

**Comment by davidlmobley** [comment]
Updated to address issue #34 , which I will mark as closed.

**Comment by davidlmobley** [comment]
@nividic - can you help me out here? The tests are failing because it can't find mdtraj, but I don't seem to have done anything which would have broken that. I've tried modifying `install.sh` to add mdtraj (it wasn't asking for this for some reason...) but this seems not to have done the trick. 

It's unclear to me why this WAS working but now is not, since it would have required mdtraj all along... Ah, except now I think I see -- now I have an `__init__.py` which imports the whole solvated_mixtures rather than just MixtureSystem, which may mean that mdtraj gets carried along by the tests when it wasn't before.

I'll see if changing that affects this.

**Comment by davidlmobley** [comment]
Hmm, it seems like it COULD be achieved that way, but I actually think we want to have the tests pull down mdtraj, as ultimately I'll want to move to testing the whole thing via travis (which we can do via getting travis to install the OpenEye tools as well - which there is now a way to do). Can you help with this?

**Comment by nividic** [comment]
Hi There,

Do you still need help on this?

Cheers,

Gaetano

**Comment by davidlmobley** [comment]
Yes.


On Mon, Apr 18, 2016 at 10:26 AM, nividic <notifications@github.com> wrote:

> Hi There,
>
> Do you still need help on this?
>
> Cheers,
>
> Gaetano
>
> On 04/15/2016 05:38 PM, David L. Mobley wrote:
> >
> > @nividic <https://github.com/nividic> - can you help me out here? The
> > tests are failing because it can't find mdtraj, but I don't seem to
> > have done anything which would have broken that. I've tried modifying
> > |install.sh| to add mdtraj (it wasn't asking for this for some
> > reason...) but this seems not to have done the trick.
> >
> > It's unclear to me why this WAS working but now is not, since it would
> > have required mdtraj all along... Ah, except now I think I see -- now
> > I have an |__init__.py| which imports the whole solvated_mixtures
> > rather than just MixtureSystem, which may mean that mdtraj gets
> > carried along by the tests when it wasn't before.
> >
> > I'll see if changing that affects this.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/MobleyLab/SolvationToolkit/pull/37#issuecomment-210698195
> >
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/MobleyLab/SolvationToolkit/pull/37#issuecomment-211486205>
>



-- 
David Mobley
dmobley@gmail.com
949-385-2436

**Comment by davidlmobley** [comment]
@nividic - test is running again.

**Comment by davidlmobley** [comment]
Thanks, @nividic - looks like this is ready to merge (it's passing tests). I'm just going to wait to see if @camizanette is in the midst of changing something else before I merge, since it will be easier for her if she doesn't have to figure out how to merge these changes into hers.

**Comment by davidlmobley** [comment]
Updated this to also include @camizanette 's changes from #41 , fixing bond orders in .sdf files.

**Comment by davidlmobley** [comment]
Passes checks. Merging. @bannanc , please note that this initiates version tags.

**Pull request merged**
