### PR TITLE
API changes to allow specification by mole fraction and completely rework constructor/component addition (not quite complete)

### PR DESCRIPTION
**Pull request by nividic**
(will fill in in a minute)

### CODE REVIEW

**Comment by nividic** [comment]
I cleaned the code and start adding comments. It is still missing the testing part for travis and therefore travis is failing

**Comment by davidlmobley** [comment]
The above is a complete first pass at implementing https://github.com/MobleyLab/SolvationToolkit/issues/60 and appears to be somewhat functional. Because @nividic is out of town and I need this finished, I am working on finishing this via some code cleanup/error checking additions, fixing the tests via travis, and so on.

Because I don't have access to his fork and he is away from internet for more than a week, my tentative plan is to finish getting fixes in place to finalize this locally on my machine, then when they are working, merge this PR and immediately submit a new PR which would bring my local changes in to the main branch so there will only be a few minutes during which this code is live but my local changes are not yet live.

**Comment by davidlmobley** [comment]
Please note that this PR will bring major changes to the API, i.e.:

```python
mixture = MixtureSystem()
mixture.addComponent(label='phenol', smiles='c1ccc(cc1)O', number=1)
mixture.addComponent(label='toluene', smiles='Cc1ccccc1', number=10)
mixture.addComponent(label='cyclohexane', smiles='C1CCCCC1', number=500)
mixture.build(prmtop_filename='mixture.prmtop', inpcrd_filename='mixture.inpcrd')
```

and 
```python
liquid = MixtureSystem()
liquid.addComponent('water')

binary_mixture = MixtureSystem()
binary_mixture.addComponent(name='water', mole_fraction=0.2)
binary_mixture.addComponent(name='methanol') # assumed to be rest of mixture if no mole_fraction specified

ternary_mixture = MixtureSystem()
binary_mixture.addComponent(name='ethanol', mole_fraction=0.2)
binary_mixture.addComponent(name='methanol', mole_fraction=0.2)
ternary_mixture.addComponent(name='water')

infinite_dilution = MixtureSystem()
infinite_dilution.addComponent(name='phenol', mole_fraction=0.0) # infinite dilution
infinite_dilution.addComponent(name='water')
```

rather than the existing format, which would be more like
```python
builder = MixtureSystem( ['phenol', 'toluene'], ['c1ccc(cc1)O','Cc1ccccc1'], [1, 10], 'data' )
```

**Comment by davidlmobley** [comment]
For the record, @nividic - it's SMILES strings, not SMILE strings: https://en.wikipedia.org/wiki/Simplified_molecular-input_line-entry_system

**Comment by davidlmobley** [comment]
OK, so I have a set of local fixes that I think will make the tests work. I'm going to switch this from [WIP] and merge (temporarily breaking things) then submit a new PR that will provide the following changes:

- Updated version string debugging info in solvated_mixtures.py
- Length updates to doc string and comments
- Doc string updates for MixtureSystem
- Error message clarifications
- Updates to ensure failures to generate SMILES are caught
- Update version string to 0.3.0.dev0
- Switch every instance of "smile" as in "smile string" to "smiles" as is proper.
- Replace the "numbers" of each component with the "number" of each component since each component has ONE number of monomers
- Move creation of GROMACS and AMBER file names into the build function, as these are not known on construction
- Move initialization of lists of components (smiles, number of molecules, etc) into the build section as these are not final until we build
- Fix function of "solute_index"
- Tests changes:
    - REQUIRE OpenEye for testing and usage now that it is working on Travis
    - Totally rewrite all tests

**Pull request merged**
